# Generated by Django 2.1.7 on 2019-03-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0002_auto_20190329_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='ProfilePicture',
        ),
    ]
