# Generated by Django 2.1.7 on 2019-04-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersauth', '0004_auto_20190421_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_type',
            field=models.CharField(choices=[('standard', 'standard'), ('hotel_owner', 'hotel_owner'), ('restaurant_owner', 'restaurant_owner')], default='standard', max_length=7),
        ),
    ]
