# Generated by Django 2.1.7 on 2019-03-04 15:43

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('siahatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_Time', models.TimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ticket_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Attractions',
            },
        ),
        migrations.CreateModel(
            name='R_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_cost', models.IntegerField(blank=True, null=True)),
                ('_type', models.CharField(choices=[('food', 'FOOD'), ('drink', 'DRINK'), ('other', 'OTHER')], default='food', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'R_menus',
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_Time', models.TimeField(auto_now_add=True)),
                ('url_Picture', django_mysql.models.ListTextField(models.URLField(max_length=500), size=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('star_Rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('star_Rating', models.IntegerField(blank=True, null=True)),
                ('_type', models.CharField(choices=[('hotel', 'HOTEL'), ('restaurant', 'RESTAURANT'), ('poi', 'POINT_OF_INTERET')], default='hotel', max_length=6)),
                ('type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
