# Generated by Django 2.1.7 on 2019-03-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siahatapp', '0003_auto_20190304_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_menu',
            name='restaurant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siahatapp.Restaurants'),
        ),
    ]
