# Generated by Django 2.1.7 on 2019-03-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siahatapp', '0004_r_menu_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='r_menu',
            old_name='_type',
            new_name='item_type',
        ),
    ]
