# Generated by Django 2.1.7 on 2019-04-20 18:16

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siahatapp', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
